# Generated by Django 5.1 on 2024-08-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_student_last_login_alter_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
